<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="EQ-EQ6330754" name="TestCases.MaintenancePlusOnsiteInterventionScopeProcessingAMTestCase" tests="14" failures="2" timestamp="25 Aug 2020 11:03:25 GMT" time="1309.278" errors="0">
  <testcase name="newCaseGeneration" time="202.578" classname="TestCases.MaintenancePlusOnsiteInterventionScopeProcessingAMTestCase"/>
  <testcase name="checkManageStatusInGold" time="141.761" classname="TestCases.MaintenancePlusOnsiteInterventionScopeProcessingAMTestCase"/>
  <testcase name="onsiteIntervention" time="82.468" classname="TestCases.MaintenancePlusOnsiteInterventionScopeProcessingAMTestCase"/>
  <testcase name="taskCompletionWithProcurementUser" time="99.540" classname="TestCases.MaintenancePlusOnsiteInterventionScopeProcessingAMTestCase"/>
  <testcase name="checkRFS_RFBACheckinGold" time="97.951" classname="TestCases.MaintenancePlusOnsiteInterventionScopeProcessingAMTestCase">
    <failure type="java.lang.AssertionError" message="expected [Acceptance] but found [Manage]">
      <![CDATA[java.lang.AssertionError: expected [Acceptance] but found [Manage]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at themis.Pages.GoldOrderStatusCheckPage.statusCheck(GoldOrderStatusCheckPage.java:68)
at themis.Pages.GoldOrderStatusCheckPage.checkRFS_RFB(GoldOrderStatusCheckPage.java:97)
at TestCases.MaintenancePlusOnsiteInterventionScopeProcessingAMTestCase.checkRFS_RFBACheckinGold(MaintenancePlusOnsiteInterventionScopeProcessingAMTestCase.java:198)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkRFS_RFBACheckinGold -->
  <testcase name="samiSupervisor" time="76.623" classname="TestCases.MaintenancePlusOnsiteInterventionScopeProcessingAMTestCase"/>
  <testcase name="SAMIUser" time="51.569" classname="TestCases.MaintenancePlusOnsiteInterventionScopeProcessingAMTestCase"/>
  <testcase name="pocmSupervisor" time="75.674" classname="TestCases.MaintenancePlusOnsiteInterventionScopeProcessingAMTestCase"/>
  <testcase name="pocmUser" time="42.300" classname="TestCases.MaintenancePlusOnsiteInterventionScopeProcessingAMTestCase"/>
  <testcase name="acceptanceIS" time="150.098" classname="TestCases.MaintenancePlusOnsiteInterventionScopeProcessingAMTestCase"/>
  <testcase name="billingSupervisor" time="84.127" classname="TestCases.MaintenancePlusOnsiteInterventionScopeProcessingAMTestCase"/>
  <testcase name="billingUser1" time="58.282" classname="TestCases.MaintenancePlusOnsiteInterventionScopeProcessingAMTestCase"/>
  <testcase name="checkCompletedTasks" time="52.268" classname="TestCases.MaintenancePlusOnsiteInterventionScopeProcessingAMTestCase">
    <failure type="java.lang.AssertionError" message="expected [Completed] but found [New]">
      <![CDATA[java.lang.AssertionError: expected [Completed] but found [New]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at themis.Pages.TaskCompletionPage.checkCloseTasks_Maintenance(TaskCompletionPage.java:879)
at TestCases.MaintenancePlusOnsiteInterventionScopeProcessingAMTestCase.checkCompletedTasks(MaintenancePlusOnsiteInterventionScopeProcessingAMTestCase.java:293)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkCompletedTasks -->
  <testcase name="checkGoldOrderAcceptanceStatus" time="94.039" classname="TestCases.MaintenancePlusOnsiteInterventionScopeProcessingAMTestCase"/>
</testsuite> <!-- TestCases.MaintenancePlusOnsiteInterventionScopeProcessingAMTestCase -->
